PRO_DIR : "H:/Classic_Autosar_02/02_hfw"
FOLDER_GENERATOR : "C:/EB/tresos"
FOLDER_OZONE : "H:/01_SEGGER/Ozone/Ozone.exe"
FOLDER_JLINK : "H:/01_SEGGER/JLink/JLink.exe"
DEBUGGER_T32_EXE : "H:/00_Compiler/TRACE32_R_2023_02_000159199/files/bin/windows64/t32marm.exe"
FOLDER_GCC : "H:/00_Compiler/GCC_102"
FOLDER_IAR : "H:/00_Compiler/IAR Systems/Embedded Workbench 8.4/arm"
FOLDER_PYTHON : "H:/02_Python310"
FOLDER_T32_INSTALL : "H:/00_Compiler/TRACE32_R_2023_02_000159199/files"