#======================================= Begin User Config ============================
TEST_NAME = 'TEST_NAME_M4'
TEST_MODULE = 'TEST_MODULE_M4'
TEST_COMPILER = 'TEST_COMPILER_M4'   # gcc/iar/ghs/ghs_c/keilC
GET_LINE_FAILED = 'GET_LINE_FAILED_M4' # True
TEST_PC_COM_PORT = 'TEST_PC_COM_PORT_M4' # Open device manager to get
TEST_CORE_LIST = 'TEST_CORE_LIST_M4' # M7_CORE0/M4_CORE1/M7_CORE0_and_M4_CORE1. If TEST_CORE_LIST = '' then default run on M7_CORE0
SILICON_NAME = 'SILICON_NAME_M4' # S32K144/STM32F407VG/STM32H755ZI/   DEVICE =STM32H755ZI_M7/STM32H755ZI_M4   DEVICE = SILICON_NAME + '_' + TEST_CORE_LIST.split("_")[0]
SILICON_FAMILY = 'SILICON_FAMILY_M4' # STM32H7XX/STM32F4XX
DEBUGGER_JLINK_INTERFACE = 'DEBUGGER_JLINK_INTERFACE_M4' # IP  USB
DEBUGGER_SERIAL_NUMBER = 'DEBUGGER_SERIAL_NUMBER_M4' # (621000000/ 59768862)  If DEBUGGER_JLINK_INTERFACE = USB
DEBUGGER_JLINK_IP = 'DEBUGGER_JLINK_IP_M4' # If JLINK_INTERFACE = IP 192.168.1.6   tunnel:59768862::jlink-asia.segger.com
FOLDER_T32_INSTALL = 'FOLDER_T32_INSTALL_M4'
DEBUGGER_T32_EXE = 'DEBUGGER_T32_EXE_M4'
FOLDER_PYTHON = 'FOLDER_PYTHON_M4'
FOLDER_GCC = 'FOLDER_GCC_M4'
FOLDER_IAR = 'FOLDER_IAR_M4'
FOLDER_GENERATOR = 'FOLDER_GENERATOR_M4'
FOLDER_OZONE = 'FOLDER_OZONE_M4'
FOLDER_JLINK = 'FOLDER_JLINK_M4'
PRO_DIR = 'PRO_DIR_M4'
FOLDER_TEST_PRODIR = f'{PRO_DIR}/tests_new/{SILICON_NAME}'
FOLDER_FRAMEWORK_PRODIR = f'{PRO_DIR}'
FOLDER_PLUGIN = f'{FOLDER_GENERATOR}/plugins'
FOLDER_OUTPUT = f'{PRO_DIR}/zOutput'
#======================================= End User Config ==============================
#======================================= Begin Read Only ==============================
PLUGIN_COMMON_NAME = 'PLUGIN_COMMON_NAME_M4'
TEST_PROJECT = "EbProject"
TEST_GENERATER = 'Eb_Tresos'
TEST_DEBUGGER = 'TEST_DEBUGGER_M4'  # ozone/lauterbach
TEST_EPD_TYPE = 'TEST_EPD_TYPE_M4' # epd@asc:4.4.0
DEBUGGER_INTERFACE = 'DEBUGGER_INTERFACE_M4'  # JTAG/ SWD
FOLDER_EB_TESTPROJECT = f'{FOLDER_TEST_PRODIR}/build_env/{TEST_PROJECT}'
LINKER_FILE_FLASH_OR_RAM = 'LINKER_FILE_FLASH_OR_RAM_M4'  # flash/ram
GEN_EPD_BY_RESOURCE = 'GEN_EPD_BY_RESOURCE_M4' # STM32H7XX_lqfp144/STM32F4XX_lqfp144
PRE_EXECUTE_CMD = None
POST_EXECUTE_CMD = None
#======================================= End Read Only ===============================
#======================================= Begin M4 Replace ============================
M4_TARGET_ARCHITECTURE = 'M4_TARGET_ARCHITECTURE_M4' # CORTEXM
M4_HW_SILICON_NAME = f'{SILICON_NAME}'
M4_EB_VERSION = 'M4_EB_VERSION_M4' # 28.2.0
M4_SOFTWARE_VERSION = 'M4_SOFTWARE_VERSION_M4' # 0.9.0 BETA
M4_HW_RELEASE_NAME = f'{PLUGIN_COMMON_NAME}'
M4_TEST_PROJECT = f'{TEST_PROJECT}'
#======================================= End M4 Replace ==============================